plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.androidx.baselineprofile)
    `maven-publish`
}

group = property("GROUP") as String
version = property("VERSION_NAME") as String

android {
    namespace = "des.c5inco.torph.compose"
    compileSdk = libs.versions.compileSdk.get().toInt()
    defaultConfig {
        minSdk = libs.versions.minSdk.get().toInt()
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    buildFeatures { compose = true }
    publishing { singleVariant("release") { withSourcesJar() } }
}

kotlin {
    jvmToolchain(17)
    explicitApi()
}

// Baseline Profile for this library and torph-core, generated by :benchmark's
// BaselineProfileGenerator driving :demo, and shipped in the AAR so apps compile the
// text-change path ahead of time. Regenerate with ./gradlew :torph-compose:generateBaselineProfile.
baselineProfile {
    filter { include("des.c5inco.torph.**") }
}

dependencies {
    baselineProfile(project(":benchmark"))
    api(project(":torph-core"))
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.foundation)
    implementation(libs.compose.animation)
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.text)
    implementation(libs.kotlinx.coroutines.core)

    androidTestImplementation(platform(libs.compose.bom))
    androidTestImplementation(libs.androidx.junit)
    // Pin androidx.test above what ui-test-junit4 pulls in (espresso 3.5.0 / runner 1.5.0),
    // which crashes on Android 17 (InputManager.getInstance was removed).
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(libs.androidx.test.runner)
    androidTestImplementation(libs.androidx.test.core)
    androidTestImplementation(libs.androidx.test.monitor)
    androidTestImplementation(libs.compose.ui.test.junit4)
    debugImplementation(libs.compose.ui.test.manifest)
}

afterEvaluate {
    publishing {
        publications {
            create<MavenPublication>("release") {
                from(components["release"])
                artifactId = "torph-compose"
                pom {
                    name.set("Torph for Jetpack Compose")
                    description.set("Morphing text for Jetpack Compose. An unofficial port of lochie/torph.")
                }
            }
        }
    }
}
